name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - uses: Jimver/cuda-toolkit@v0.2.15
        id: cuda-toolkit
        with:
          cuda: '12.4.1'

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
        shell: bash

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install coverage
        run: |
          python -m pip install coverage
          python -m pip install gcovr
        shell: bash

      - name: Build and Test Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_WITH_GCOVR=ON -DBUILD_WITH_KOKKOS=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_TURING75=ON ..
          make -j20
          make coverage_xml
        env:
          CC: gcc-13
          CXX: g++-13

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true # optional (default = false)
      #     gcov: true
      #     gcov_executable: gcov-13
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
