name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 1
        shell: bash

      - name: install gcovr
        run: |
          sudo apt-get install gcovr
        shell: bash

      - name: Create build directory and run CMake
        run: cmake -S . -B build -G "Unix Makefiles"
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Build Project
        run: cmake --build build --target all -- -j20

      - name: Test Project
        run: |
          cd build
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_executable: gcov-13
          token: ${{ secrets.CODECOV_TOKEN }}
