name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    branches: [ "dev"  ]
  pull_request:
    branches: [ "main" ]
    branches: [ "dev"  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Create build directory and run CMake"
        run: cmake -S . -B build -G "Unix Makefiles"
    - name: "Build Project" 
        run: cmake --build build --target all -- -j4
    - name: "Test Project"
        run: |
          cd build
          make test
          make coverage       
