name: C/C++ CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache boost
      uses: actions/cache@v1.0.3
      id: cache-boost
      with:
        path: "~/boost"
        key: libboost-all-dev
  
    - name: Install boost
      env:
        CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'nevertrue' ]]; then
          sudo cp --force --recursive ~/boost/* /
        else
          sudo apt-get update && sudo apt-get install -yq libboost-all-dev
          mkdir -p ~/boost
          for dep in libboost-all-dev; do
            dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
          done
        fi
      
    - name: "Create build directory and run CMake"
      run: cmake -S . -B build -G "Unix Makefiles"

    - name: "Build Project" 
      run: cmake --build build --target all -- -j20

    - name: "Test Project"
      run: |
        cd build
        make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        gcov: true
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
