name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 1
        shell: bash

      - name: install gcovr
        run: |
          sudo apt-get install gcovr
        shell: bash

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install coverage
        run: |
          python -m pip install coverage
        shell: bash

      - name: Create build directory and run CMake
        run: cmake -S . -B build -G "Unix Makefiles" -DBUILD_WITH_GCOVR=ON
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Build Project
        run: cmake --build build --target all -- -j20

      - name: Test Project
        run: |
          cd build
          make coverage_xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          files: build/coverage_xml.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
