name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcc:13

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: install coverage
        run: |
          python -m venv venv
          source venv/bin/activate

          python -m pip install coverage
          python -m pip install gcovr

          deactivate
        shell: bash

      - name: install cmake
        run: |
          apt update -y
          apt install -y cmake
        shell: bash

      - name: install gcov-13
        run: |
          apt update -y
          apt install -y gcov
        shell: bash

      - name: Build and Test Project
        run: |
          source venv/bin/activate

          git config --global --add safe.directory '*'
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_WITH_GCOVR=ON ..
          make -j20
          make coverage_xml

          deactivate
        shell: bash
        env:
          CC: gcc
          CXX: g++


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
          gcov: true
          gcov_executable: gcov-13
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
