name: DEBUG BUILD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
          sudo apt install valgrind
        shell: bash

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install coverage
        run: |
          python -m pip install coverage
          python -m pip install gcovr
          python -m pip install numpy
        shell: bash

      - name: Build and Test Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_WITH_GCOVR=ON ..
          make -j20
          make coverage_xml
        env:
          CC: gcc-13
          CXX: g++-13

      - name: valgrind tests
        run: |
          cd integration_tests/cgo
          mkdir test
          cp moldescriptor.dat guff.dat run-01.in cgo-mm-00.rst test
          cd test
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ../../../build/apps/PQ run-01.in

      # - name: Run integration Tests
      #   run: |
      #     pip install pytest
      #     pip install pytest-cov
      #     pip install pqanalysis
      #     pytest integration_tests


      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true # optional (default = false)
      #     gcov: true
      #     gcov_executable: gcov-13
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
