name: RELEASE BUILD arm64

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.cmake/**'
      - 'apps/**'
      - 'include/**'
      - 'src/**'
      - 'integration_tests/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: arm64

    steps:
      - uses: actions/checkout@v3

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
        shell: bash

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install python dependencies
        run: |
          python -m pip install numpy
        shell: bash

      - name: Build and Test Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j20
          make test
        env:
          CC: gcc-13
          CXX: g++-13
