name: KOKKOS BUILD

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
        shell: bash

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install coverage
        run: |
          python -m pip install numpy
        shell: bash

      - name: Build and Test Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j20
          make test
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Run integration Tests
        run: |
          pip install pytest
          pip install pytest-cov
          pip install pqanalysis
          pytest integration_tests